### ISSUE TITLE
repo for Telegram messaging

### ISSUE THREAD

**Issue by mkeyno** [chaeplin/esp8266twitter#1]
hi @chaeplin , sorry to draw issue for my question , as you well done for twitter do you know any repo for Telegram messaging  or have any plan to develop it by yourself

**Comment by chaeplin** [comment]
check this: 
http://www.esp8266.com/viewtopic.php?f=24&t=4396
https://github.com/Gianbacchio/ESP8266-TelegramBot

**Comment by mkeyno** [comment]
tnx buddy , do you have any gitter room or else

**Comment by chaeplin** [comment]
@mkeyno no room for me. listener in https://gitter.im/esp8266/Arduino :)
